"""create model tables

Revision ID: 809651cc93a6
Revises: b05389a67795
Create Date: 2026-05-18 09:35:14.833014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '809651cc93a6'
down_revision: Union[str, None] = 'b05389a67795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('pin_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('rubric_file_id', sa.UUID(), nullable=True),
    sa.Column('module_book_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='modulestatus'), nullable=True),
    sa.ForeignKeyConstraint(['module_book_id'], ['file_records.id'], ),
    sa.ForeignKeyConstraint(['rubric_file_id'], ['file_records.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='projectstatus'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('student_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='studentstatus'), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'reviewed', 'final', name='assessmentstatus'), nullable=True),
    sa.Column('draft_form_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_form_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recording_file_id', sa.UUID(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('consent_recorded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recording_file_id'], ['file_records.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'docx', 'xlsx', 'pptx', 'markdown', 'image', 'zip', 'other', name='filetype'), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.Enum('upload', 'github', 'gitlab', name='sourcetype'), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='embeddingstatus'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('system', 'teacher', 'ai', name='auditsource'), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('supporting_quote', sa.Text(), nullable=True),
    sa.Column('missing_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overlap_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_a_id', sa.UUID(), nullable=False),
    sa.Column('student_b_id', sa.UUID(), nullable=False),
    sa.Column('evidence_a_id', sa.UUID(), nullable=False),
    sa.Column('evidence_b_id', sa.UUID(), nullable=False),
    sa.Column('overlap_type', sa.Enum('textual', 'semantic', name='overlaptype'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_a_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['evidence_b_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['student_a_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['student_b_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overlap_signals')
    op.drop_table('evidence_matches')
    op.drop_table('chat_messages')
    op.drop_table('audit_events')
    op.drop_table('evidence')
    op.drop_table('assessments')
    op.drop_table('students')
    op.drop_table('projects')
    op.drop_table('modules')
    op.drop_table('teachers')
    op.drop_table('file_records')
    # ### end Alembic commands ###
